<?php
/**
 * QC Lab DB Switcher
 * Usage: 
 *   php switch_db.php work  (สลับไปใช้ Database ที่ทำงาน)
 *   php switch_db.php home  (สลับไปใช้ Database ที่บ้าน xampp)
 */

$mode = $argv[1] ?? 'status';

$envPath = __DIR__ . '/.env';
$legacyPath = __DIR__ . '/legacy/config.php';

if (!file_exists($envPath)) {
    die("Error: .env file not found!\n");
}
if (!file_exists($legacyPath)) {
    die("Error: legacy/config.php not found!\n");
}

$envContent = file_get_contents($envPath);
$legacyContent = file_get_contents($legacyPath);

$workConfig = [
    'host' => '10.22.0.101',
    'port' => '3307',
    'db' => 'qc3',
    'user' => 'std01',
    'pass' => '9F1e-VE3Fhbq'
];

$homeConfig = [
    'host' => '127.0.0.1',
    'port' => '3306',
    'db' => 'qc',
    'user' => 'root',
    'pass' => ''
];

if ($mode !== 'work' && $mode !== 'home') {
    // Check current mode roughly by seeing what's uncommented in legacy
    $isWork = strpos($legacyContent, "\$host = '10.22.0.101';") !== false;
    echo "====================================\n";
    echo "  QC Database Switcher\n";
    echo "====================================\n";
    echo "Current Mode: " . ($isWork ? "WORK (MariaDB 10.22...)" : "HOME (XAMPP Localhost)") . "\n\n";
    echo "To switch, run:\n";
    echo "  php switch_db.php work\n";
    echo "  php switch_db.php home\n";
    exit;
}

$cfg = $mode === 'work' ? $workConfig : $homeConfig;

// 1. Update .env
$envContent = preg_replace('/^DB_HOST=.*$/m', 'DB_HOST=' . $cfg['host'], $envContent);
$envContent = preg_replace('/^DB_PORT=.*$/m', 'DB_PORT=' . $cfg['port'], $envContent);
$envContent = preg_replace('/^DB_DATABASE=.*$/m', 'DB_DATABASE=' . $cfg['db'], $envContent);
$envContent = preg_replace('/^DB_USERNAME=.*$/m', 'DB_USERNAME=' . $cfg['user'], $envContent);
$envContent = preg_replace('/^DB_PASSWORD=.*$/m', 'DB_PASSWORD=' . $cfg['pass'], $envContent);
file_put_contents($envPath, $envContent);

// 2. Update legacy/config.php
$newLegacy = "<?php
/**
 * Local Database Configuration (Auto-generated by switch_db.php)
 */

\$host = '{$cfg['host']}';
\$port = {$cfg['port']};
\$db = '{$cfg['db']}';
\$user = '{$cfg['user']}';
\$pass = '{$cfg['pass']}';
";
file_put_contents($legacyPath, $newLegacy);

// 3. Clear artisan cache if available
echo "Switching to " . strtoupper($mode) . " mode...\n";
exec('php artisan config:clear');
exec('php artisan cache:clear');

echo "Done! The project is now using the [" . strtoupper($mode) . "] database.\n";
