<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, router, usePage } from '@inertiajs/vue3';
import { computed, ref, watch } from 'vue';

const props = defineProps({ results: Object, summary: Object, filters: Object, exportTemplates: Array });
const page = usePage();
const isAdmin = computed(() => page.props.auth?.user?.role === 'admin');
const dateFrom = ref(props.filters.date_from);
const dateTo = ref(props.filters.date_to);
const dmcSearch = ref(props.filters.dmc || '');
const perPage = ref(String(props.filters.per_page ?? 25));
const reportReloadOnly = ['results', 'summary', 'filters', 'flash'];

const search = () => router.get(route('report.index'), {
    date_from: dateFrom.value,
    date_to: dateTo.value,
    dmc: dmcSearch.value,
    per_page: perPage.value,
}, {
    only: reportReloadOnly,
    preserveState: true,
    preserveScroll: true,
    replace: true,
});

const visitPage = (url) => {
    if (!url) return;

    router.visit(url, {
        only: reportReloadOnly,
        preserveState: true,
        preserveScroll: true,
        replace: true,
    });
};

const resetFilters = () => {
    const now = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);

    dateFrom.value = monthStart.toISOString().slice(0, 10);
    dateTo.value = now.toISOString().slice(0, 10);
    dmcSearch.value = '';
    perPage.value = '25';
    search();
};

const formatDate = (value) => value
    ? new Date(value).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })
    : '-';

const formatTime = (value) => value
    ? new Date(value).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })
    : '-';

const rows = computed(() => props.results?.data ?? []);
const totalRows = computed(() => props.summary?.total_rows ?? props.results?.total ?? 0);
const visibleTransactionIds = computed(() => [...new Set(rows.value.map((row) => row.transaction_id))]);

const selectedIds = ref([]);
const isSelected = (id) => selectedIds.value.includes(id);
const hasSelection = computed(() => selectedIds.value.length > 0);
const allVisibleSelected = computed(() => visibleTransactionIds.value.length > 0
    && visibleTransactionIds.value.every((id) => selectedIds.value.includes(id)));

const toggleSelectAll = (event) => {
    const visibleIds = visibleTransactionIds.value;

    if (event.target.checked) {
        selectedIds.value = [...new Set([...selectedIds.value, ...visibleIds])];
        return;
    }

    selectedIds.value = selectedIds.value.filter((id) => !visibleIds.includes(id));
};

const toggleRow = (id) => {
    selectedIds.value = selectedIds.value.includes(id)
        ? selectedIds.value.filter((item) => item !== id)
        : [...selectedIds.value, id];
};

watch(
    () => [props.results?.current_page, props.filters.date_from, props.filters.date_to, props.filters.dmc, props.filters.per_page],
    () => {
        selectedIds.value = [];
    },
);

const showExportModal = ref(false);
const customFilename = ref('');
const exportMode = ref('all');
const selectedTemplateKey = ref('standard');
const selectedTemplateSheet = ref('');
const exportBusy = ref(false);
const exportError = ref('');
const supportsSavePicker = computed(() => typeof window !== 'undefined' && 'showSaveFilePicker' in window);
const availableExportTemplates = computed(() => (
    Array.isArray(props.exportTemplates) && props.exportTemplates.length > 0
        ? props.exportTemplates
        : [{ key: 'standard', label: 'Standard Table', description: 'Default export generated by the system.' }]
));
const selectedTemplate = computed(() => (
    availableExportTemplates.value.find((template) => template.key === selectedTemplateKey.value)
    || availableExportTemplates.value[0]
    || null
));
const selectedTemplateSheets = computed(() => {
    const sheets = selectedTemplate.value?.sheet_names;
    return Array.isArray(sheets) ? sheets : [];
});

watch(selectedTemplateKey, () => {
    const preferred = selectedTemplate.value?.default_sheet_name || '';
    const availableSheets = selectedTemplateSheets.value;

    if (availableSheets.length === 0) {
        selectedTemplateSheet.value = '';
        return;
    }

    if (preferred && availableSheets.includes(preferred)) {
        selectedTemplateSheet.value = preferred;
        return;
    }

    selectedTemplateSheet.value = availableSheets[0];
});

const openExport = (mode) => {
    exportMode.value = mode;
    customFilename.value = `QC_Report_${dateFrom.value}_to_${dateTo.value}`;
    selectedTemplateKey.value = availableExportTemplates.value.some((template) => template.key === selectedTemplateKey.value)
        ? selectedTemplateKey.value
        : availableExportTemplates.value[0].key;
    const preferred = selectedTemplate.value?.default_sheet_name || '';
    const availableSheets = selectedTemplateSheets.value;
    selectedTemplateSheet.value = availableSheets.includes(preferred) ? preferred : (availableSheets[0] || '');
    exportError.value = '';
    showExportModal.value = true;
};

const normalizedExportFilename = computed(() => {
    const base = (customFilename.value || 'export').trim() || 'export';
    return base.toLowerCase().endsWith('.xlsx') ? base : `${base}.xlsx`;
});

const buildExportUrl = () => {
    const ids = exportMode.value === 'selected' ? selectedIds.value.join(',') : 'all';
    const query = new URLSearchParams({
        ids,
        date_from: dateFrom.value,
        date_to: dateTo.value,
        dmc: dmcSearch.value || '',
        filename: customFilename.value || 'export',
        template_key: selectedTemplateKey.value || 'standard',
    });

    if (selectedTemplateSheet.value) {
        query.set('template_sheet', selectedTemplateSheet.value);
    }

    return `${route('report.export')}?${query.toString()}`;
};

const fallbackBrowserDownload = (url) => {
    window.location.href = url;
};

const saveWithPicker = async (url) => {
    const handle = await window.showSaveFilePicker({
        suggestedName: normalizedExportFilename.value,
        types: [
            {
                description: 'Excel workbook',
                accept: {
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'],
                },
            },
        ],
    });

    const response = await fetch(url, {
        method: 'GET',
        credentials: 'same-origin',
        headers: {
            'X-Requested-With': 'XMLHttpRequest',
        },
    });

    if (!response.ok) {
        const message = await response.text();
        throw new Error(message || `Export request failed with status ${response.status}`);
    }

    const blob = await response.blob();
    const writable = await handle.createWritable();
    await writable.write(blob);
    await writable.close();
};

const doExport = async () => {
    const url = buildExportUrl();
    exportBusy.value = true;
    exportError.value = '';

    try {
        if (supportsSavePicker.value) {
            await saveWithPicker(url);
        } else {
            fallbackBrowserDownload(url);
        }

        showExportModal.value = false;
    } catch (error) {
        if (error?.name === 'AbortError') {
            return;
        }

        const serverMessage = typeof error?.message === 'string' ? error.message.replace(/<[^>]*>/g, ' ').trim() : '';
        exportError.value = serverMessage || (supportsSavePicker.value
            ? 'Could not save the file to the selected path. You can try again or use the browser download fallback.'
            : 'Could not start the browser download.');
    } finally {
        exportBusy.value = false;
    }
};
</script>

<template>
    <Head title="Report" />
    <AuthenticatedLayout>
        <template #title>Report</template>
        
        <div class="space-y-5">
            <div class="pg-header">
                <div>
                    <h1 class="pg-title">Report</h1>
                    <p class="pg-sub">Review completed results with lighter table payloads and export only what you need.</p>
                </div>
                <Link
                    v-if="isAdmin"
                    :href="route('report.templates.index')"
                    class="export-btn export-btn-outline"
                    style="text-decoration:none"
                >
                    Manage Excel Forms
                </Link>
            </div>

            <section class="card card-fill report-toolbar">
                <div class="report-toolbar__bar">
                    <input v-model="dmcSearch" @keyup.enter="search" type="text" placeholder="Search DMC..." class="form-inp report-filter-input report-filter-input-search">
                    <input v-model="dateFrom" type="date" class="form-inp report-filter-input">
                    <input v-model="dateTo" type="date" class="form-inp report-filter-input">
                    <select v-model="perPage" class="form-inp report-filter-input report-filter-input-select">
                        <option value="25">25 / page</option>
                        <option value="50">50 / page</option>
                        <option value="100">100 / page</option>
                        <option value="200">200 / page</option>
                    </select>
                </div>
                <div class="report-toolbar__footer">
                    <div class="report-toolbar__meta">
                        <span class="report-toolbar__tag">Filters</span>
                        <span class="report-toolbar__hint">DMC, date range, and row count</span>
                    </div>
                    <div class="report-toolbar__actions">
                        <button @click="resetFilters" class="export-btn export-btn-outline">Reset</button>
                        <button @click="search" class="export-btn export-btn-primary">Apply</button>
                    </div>
                </div>
            </section>
            
            <div class="report-meta">
                    <div class="report-meta__stats">
                        <div>
                            Showing <strong>{{ props.results?.from ?? 0 }}-{{ props.results?.to ?? 0 }}</strong> of <strong>{{ totalRows }}</strong> result(s)
                        </div>
                        <div v-if="totalRows > 0" class="report-pill-row">
                            <div class="report-summary-pill report-summary-pill-ok">{{ props.summary?.ok_count ?? 0 }} OK</div>
                            <div class="report-summary-pill report-summary-pill-ng">{{ props.summary?.ng_count ?? 0 }} NG</div>
                        </div>
                        <div v-if="hasSelection" class="report-summary-pill report-summary-pill-selected">
                            {{ selectedIds.length }} job(s) selected
                        </div>
                    </div>
                    <div class="report-meta__actions">
                        <button v-if="hasSelection" @click="openExport('selected')" class="export-btn export-btn-primary">
                            <svg style="width:14px;height:14px" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                            Export Selected
                        </button>
                        <button v-if="totalRows > 0" @click="openExport('all')" class="export-btn export-btn-outline">
                            <svg style="width:14px;height:14px" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                            Export All
                        </button>
                    </div>
            </div>

            <section class="card card-fill">
                    <div class="tbl" style="margin-bottom:0">
                        <table v-if="rows.length">
                    <thead>
                        <tr>
                            <th style="width:36px;text-align:center">
                                <input type="checkbox" :checked="allVisibleSelected" @change="toggleSelectAll" class="row-check" />
                            </th>
                            <th>Line</th>
                            <th>Date</th>
                            <th>Sender</th>
                            <th>DMC</th>
                            <th>Detail</th>
                            <th>Process</th>
                            <th>Inspector</th>
                            <th>Start</th>
                            <th>End</th>
                            <th>Result</th>
                            <th>Remark</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="r in rows" :key="`${r.transaction_id}-${r.method_name}-${r.start_time ?? 'pending'}`" :class="{ 'row-selected': isSelected(r.transaction_id) }">
                            <td style="text-align:center">
                                <input type="checkbox" :checked="isSelected(r.transaction_id)" @change="toggleRow(r.transaction_id)" class="row-check" />
                            </td>
                            <td>{{ r.line || 'โ€”' }}</td>
                            <td style="font-size:11px">{{ formatDate(r.receive_date) }}</td>
                            <td>{{ r.sender }}</td>
                            <td style="font-weight:700">{{ r.dmc || 'โ€”' }}</td>
                            <td>{{ r.detail }}</td>
                            <td>{{ r.method_name }}</td>
                            <td>{{ r.inspector }}</td>
                            <td style="font-size:11px">{{ r.start_time ? new Date(r.start_time).toLocaleTimeString('en-GB', {hour:'2-digit',minute:'2-digit'}) : 'โ€”' }}</td>
                            <td style="font-size:11px">{{ r.end_time ? new Date(r.end_time).toLocaleTimeString('en-GB', {hour:'2-digit',minute:'2-digit'}) : 'โ€”' }}</td>
                            <td>
                                <span v-if="r.judgement === 'OK'" class="pill pill-g">OK</span>
                                <span v-else-if="r.judgement === 'NG'" class="pill pill-r">NG</span>
                                <span v-else class="pill pill-y">{{ r.judgement }}</span>
                            </td>
                            <td style="font-size:11px;color:#78716c">{{ r.remark || '' }}</td>
                        </tr>
                    </tbody>
                        </table>
                        <div v-else class="report-empty-state">
                            No results found. Try adjusting the date range or DMC filter.
                        </div>
                    </div>

                    <div class="report-pagination">
                        <div class="report-pagination__summary">
                            Page {{ props.results?.current_page ?? 1 }} of {{ props.results?.last_page ?? 1 }}
                        </div>
                        <div class="report-pagination__links">
                            <button
                                v-for="(link, index) in (props.results?.links ?? [])"
                                :key="index"
                                :disabled="!link.url"
                                @click="visitPage(link.url)"
                                class="pager-btn"
                                :class="{ 'pager-btn-active': link.active }"
                                v-html="link.label"
                            />
                        </div>
                    </div>
            </section>
        </div>

        <Teleport to="body">
            <div v-if="showExportModal" class="modal-overlay" @click.self="showExportModal = false">
                <div class="modal-card">
                    <div class="modal-header">
                        <h3 class="modal-title">Export to Excel</h3>
                        <button class="modal-close" @click="showExportModal = false">ร—</button>
                    </div>
                    <div class="modal-body">
                        <label class="modal-label">File name</label>
                        <div style="display:flex;align-items:center;gap:0">
                            <input v-model="customFilename" type="text" class="modal-input" placeholder="Enter file name" @keyup.enter="doExport" autofocus />
                            <span class="modal-ext">.xlsx</span>
                        </div>
                        <label class="modal-label" style="margin-top:12px">Excel Form</label>
                        <select v-model="selectedTemplateKey" class="modal-select">
                            <option v-for="template in availableExportTemplates" :key="template.key" :value="template.key">
                                {{ template.label }}
                            </option>
                        </select>
                        <template v-if="selectedTemplateSheets.length">
                            <label class="modal-label" style="margin-top:12px">Sheet</label>
                            <select v-model="selectedTemplateSheet" class="modal-select">
                                <option v-for="sheet in selectedTemplateSheets" :key="sheet" :value="sheet">
                                    {{ sheet }}
                                </option>
                            </select>
                        </template>
                        <div class="modal-hint">
                            {{ availableExportTemplates.find((template) => template.key === selectedTemplateKey)?.description || 'Default export template.' }}
                        </div>
                        <div class="modal-hint">{{ exportMode === 'selected' ? `${selectedIds.length} job(s) selected` : `All ${totalRows} result(s)` }}</div>
                        <div class="modal-hint" v-if="supportsSavePicker">A save dialog will let you choose the folder and file path before saving the Excel file.</div>
                        <div v-if="exportError" class="modal-error">{{ exportError }}</div>
                    </div>
                    <div class="modal-footer">
                        <button class="export-btn export-btn-outline" :disabled="exportBusy" @click="showExportModal = false">Cancel</button>
                        <button class="export-btn export-btn-primary" :disabled="exportBusy" @click="doExport">
                            <svg style="width:14px;height:14px" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                            {{ exportBusy ? 'Preparing...' : (supportsSavePicker ? 'Choose Path & Save' : 'Download') }}
                        </button>
                    </div>
                </div>
            </div>
        </Teleport>
    </AuthenticatedLayout>
</template>

<style scoped>
.report-toolbar {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 14px 18px;
    background: linear-gradient(180deg, rgba(24, 18, 14, 0.96), rgba(17, 12, 10, 0.98));
}

.report-toolbar__bar {
    display: grid;
    grid-template-columns: minmax(240px, 1.4fr) repeat(3, minmax(120px, 0.55fr));
    gap: 10px;
    align-items: center;
}

.report-filter-input {
    min-width: 0;
    height: 40px;
    padding: 8px 12px;
    border-radius: 10px;
    background: rgba(7, 7, 7, 0.52);
    border: 1px solid rgba(255, 255, 255, 0.08);
    color: #fafaf9;
    font-size: 13px;
}

.report-filter-input:focus {
    border-color: rgba(251, 146, 60, 0.32);
    box-shadow: 0 0 0 3px rgba(251, 146, 60, 0.08);
}

.report-toolbar__footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    flex-wrap: wrap;
}

.report-toolbar__meta {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
}

.report-toolbar__tag {
    display: inline-flex;
    align-items: center;
    padding: 4px 8px;
    border-radius: 999px;
    background: rgba(251, 146, 60, 0.08);
    border: 1px solid rgba(251, 146, 60, 0.18);
    color: #fdba74;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.08em;
    text-transform: uppercase;
}

.report-toolbar__hint {
    color: #a8a29e;
    font-size: 12px;
    line-height: 1.4;
}

.report-toolbar__actions {
    display: flex;
    align-items: center;
    gap: 8px;
}

.report-meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    flex-wrap: wrap;
}

.report-meta__stats {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 12px;
    color: #a8a29e;
    font-size: 12px;
}

.report-meta__stats strong {
    color: #fafaf9;
}

.report-meta__actions {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
}

.report-pill-row {
    display: flex;
    gap: 8px;
    font-size: 11px;
    font-weight: 600;
}

.report-summary-pill {
    padding: 2px 8px;
    border-radius: 999px;
    border: 1px solid rgba(255, 255, 255, 0.08);
}

.report-summary-pill-ok {
    background: rgba(34, 197, 94, 0.12);
    border-color: rgba(34, 197, 94, 0.2);
    color: #86efac;
}

.report-summary-pill-ng {
    background: rgba(244, 63, 94, 0.12);
    border-color: rgba(244, 63, 94, 0.18);
    color: #fecdd3;
}

.report-summary-pill-selected {
    background: rgba(251, 146, 60, 0.14);
    border-color: rgba(251, 146, 60, 0.2);
    color: #fdba74;
    font-size: 11px;
    font-weight: 600;
}

.report-empty-state {
    padding: 40px;
    text-align: center;
    color: #a8a29e;
    font-size: 13px;
    background: rgba(18, 18, 18, 0.92);
    border-radius: 16px;
    border: 1px solid rgba(255, 255, 255, 0.08);
}

.report-shell {
    padding: 18px;
}

.report-shell__meta {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    margin-bottom: 18px;
    flex-wrap: wrap;
}

.report-shell__line,
.report-shell__pill,
.report-shell__cell {
    position: relative;
    overflow: hidden;
    background: rgba(255, 255, 255, 0.06);
    border-radius: 999px;
}

.report-shell__line::after,
.report-shell__pill::after,
.report-shell__cell::after,
.cert-shell__card::after,
.cert-shell__line::after,
.cert-shell__button::after {
    content: '';
    position: absolute;
    inset: 0;
    transform: translateX(-100%);
    background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.14), transparent);
    animation: shell-shimmer 1.25s ease-in-out infinite;
}

.report-shell__line {
    height: 14px;
    width: 220px;
}

.report-shell__line-wide {
    width: 320px;
}

.report-shell__pill-row {
    display: flex;
    gap: 8px;
}

.report-shell__pill {
    width: 68px;
    height: 24px;
}

.report-shell__table {
    display: grid;
    gap: 10px;
}

.report-shell__row {
    display: grid;
    grid-template-columns: 42px 1.1fr 1.6fr 1fr 96px;
    gap: 10px;
    padding: 12px;
    border-radius: 14px;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid rgba(255, 255, 255, 0.06);
}

.report-shell__cell {
    height: 14px;
    border-radius: 10px;
}

.report-shell__cell-sm {
    width: 42px;
}

.report-shell__cell-lg {
    width: 100%;
}

.report-pagination {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 12px;
    flex-wrap: wrap;
    margin-top: 18px;
    padding-top: 18px;
    border-top: 1px solid rgba(255, 255, 255, 0.08);
}

.report-pagination__summary {
    color: #a8a29e;
    font-size: 12px;
}

.report-pagination__links {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-end;
    gap: 8px;
}

.pager-btn {
    min-width: 40px;
    padding: 8px 12px;
    border-radius: 10px;
    border: 1px solid rgba(255, 255, 255, 0.1);
    background: rgba(255, 255, 255, 0.03);
    color: #e7e5e4;
    font-size: 12px;
    transition: all 0.15s ease;
}

.pager-btn:hover:not(:disabled) {
    background: rgba(251, 146, 60, 0.08);
    border-color: rgba(251, 146, 60, 0.18);
}

.pager-btn:disabled {
    opacity: 0.4;
    cursor: not-allowed;
}

.pager-btn-active {
    background: linear-gradient(135deg, #fb923c, #ea580c);
    color: #1c1917;
    border-color: transparent;
}

:global(.theme-shell[data-theme='light'] .report-pagination__summary) {
    color: #57534e;
}

:global(.theme-shell[data-theme='light'] .pager-btn) {
    background: rgba(255, 255, 255, 0.94);
    border-color: rgba(68, 64, 60, 0.14);
    color: #57534e;
    box-shadow: 0 8px 20px rgba(24, 24, 27, 0.04);
}

:global(.theme-shell[data-theme='light'] .pager-btn:hover:not(:disabled)) {
    background: rgba(24, 24, 27, 0.04);
    border-color: rgba(68, 64, 60, 0.18);
    color: #18181b;
}

:global(.theme-shell[data-theme='light'] .pager-btn:disabled) {
    opacity: 0.62;
    color: #a8a29e;
    background: rgba(255, 255, 255, 0.84);
}

:global(.theme-shell[data-theme='light'] .pager-btn-active) {
    color: #ffffff;
    background: linear-gradient(135deg, #1d4ed8, #1e40af);
    box-shadow: 0 12px 24px rgba(29, 78, 216, 0.22);
}

.row-check {
    width: 16px;
    height: 16px;
    accent-color: #f97316;
    cursor: pointer;
}

.row-selected {
    background: linear-gradient(90deg, rgba(251, 146, 60, 0.12), rgba(15, 15, 15, 0.92)) !important;
}

.export-btn {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 6px 14px;
    font-size: 12px;
    font-weight: 600;
    font-family: inherit;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.15s ease;
    border: 1px solid transparent;
    border-radius: 999px;
}

.export-btn-primary {
    background: linear-gradient(135deg, #fb923c, #ea580c);
    color: #1c1917;
    box-shadow: 0 14px 26px rgba(249, 115, 22, 0.2);
}

.export-btn-primary:hover {
    transform: translateY(-1px);
    box-shadow: 0 18px 30px rgba(249, 115, 22, 0.24);
}

.export-btn-outline {
    background: rgba(255, 255, 255, 0.03);
    color: #f5f5f4;
    border-color: rgba(255, 255, 255, 0.1);
}

.export-btn-outline:hover {
    background: rgba(251, 146, 60, 0.08);
    border-color: rgba(251, 146, 60, 0.2);
}

/* Modal */
.modal-overlay {
    position: fixed; inset: 0; background: rgba(0,0,0,0.68); backdrop-filter: blur(8px); display: flex; align-items: center; justify-content: center; z-index: 9999;
    animation: fadeIn 0.15s ease;
}
.modal-card {
    background: linear-gradient(180deg, rgba(22, 22, 22, 0.98), rgba(12, 12, 12, 0.98));
    border: 1px solid rgba(251, 146, 60, 0.14);
    border-radius: 20px; width: 420px; max-width: 90vw; box-shadow: 0 28px 70px rgba(0,0,0,0.45);
    animation: slideUp 0.2s ease;
}
.modal-header {
    display: flex; justify-content: space-between; align-items: center; padding: 16px 20px; border-bottom: 1px solid rgba(255,255,255,0.08);
}
.modal-title { font-size: 15px; font-weight: 600; color: #fafaf9; margin: 0; }
.modal-close {
    background: none; border: none; font-size: 16px; color: #a8a29e; cursor: pointer; width: 28px; height: 28px; border-radius: 999px;
    display: flex; align-items: center; justify-content: center;
}
.modal-close:hover { background: rgba(251, 146, 60, 0.08); color: #fdba74; }
.modal-body { padding: 20px; }
.modal-label { display: block; font-size: 13px; font-weight: 500; color: #d6d3d1; margin-bottom: 6px; }
.modal-input {
    flex: 1; height: 40px; padding: 0 12px; font-size: 14px; font-family: inherit; color: #fafaf9;
    background: rgba(0,0,0,0.3); border: 1px solid rgba(255,255,255,0.08); border-radius: 12px 0 0 12px; outline: none;
    transition: border-color 0.15s; box-sizing: border-box;
}
.modal-input:focus { border-color: rgba(251,146,60,0.38); background: rgba(0,0,0,0.45); }
.modal-select {
    width: 100%;
    height: 40px;
    padding: 0 12px;
    border-radius: 12px;
    font-size: 13px;
    font-family: inherit;
    color: #fafaf9;
    background: rgba(0,0,0,0.3);
    border: 1px solid rgba(255,255,255,0.08);
    outline: none;
    box-sizing: border-box;
}
.modal-select:focus { border-color: rgba(251,146,60,0.38); background: rgba(0,0,0,0.45); }
.modal-ext {
    height: 40px; padding: 0 12px; background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-left: none;
    border-radius: 0 12px 12px 0; font-size: 13px; font-weight: 500; color: #a8a29e;
    display: flex; align-items: center; box-sizing: border-box;
}
.modal-hint { font-size: 11px; color: #78716c; margin-top: 8px; }
.modal-error {
    margin-top: 10px;
    border: 1px solid rgba(248, 113, 113, 0.2);
    border-radius: 12px;
    background: rgba(127, 29, 29, 0.18);
    padding: 10px 12px;
    color: #fecaca;
    font-size: 12px;
    line-height: 1.5;
}
.modal-footer { display: flex; justify-content: flex-end; gap: 8px; padding: 12px 20px; border-top: 1px solid rgba(255,255,255,0.08); }
@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
@keyframes slideUp { from { transform: translateY(10px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
@keyframes shell-shimmer { to { transform: translateX(100%); } }

:global(.theme-shell[data-theme='light'] .report-toolbar) {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0.99), rgba(247, 250, 252, 0.97));
}

:global(.theme-shell[data-theme='light'] .report-filter-input) {
    background: rgba(255, 255, 255, 0.96);
    border-color: rgba(15, 23, 42, 0.08);
    color: #0f172a;
}

:global(.theme-shell[data-theme='light'] .report-filter-input:focus) {
    border-color: rgba(29, 78, 216, 0.28);
    box-shadow: 0 0 0 3px rgba(29, 78, 216, 0.1);
}

:global(.theme-shell[data-theme='light'] .report-toolbar__tag),
:global(.theme-shell[data-theme='light'] .report-summary-pill-selected) {
    background: rgba(219, 234, 254, 0.9);
    border-color: rgba(29, 78, 216, 0.18);
    color: #1d4ed8;
}

:global(.theme-shell[data-theme='light'] .report-meta__stats),
:global(.theme-shell[data-theme='light'] .report-empty-state),
:global(.theme-shell[data-theme='light'] .report-toolbar__hint),
:global(.theme-shell[data-theme='light'] .modal-hint),
:global(.theme-shell[data-theme='light'] .modal-label),
:global(.theme-shell[data-theme='light'] .modal-close) {
    color: #475569;
}

:global(.theme-shell[data-theme='light'] .report-meta__stats strong),
:global(.theme-shell[data-theme='light'] .modal-title) {
    color: #0f172a;
}

:global(.theme-shell[data-theme='light'] .report-empty-state) {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0.98), rgba(247, 250, 252, 0.96));
    border-color: rgba(15, 23, 42, 0.08);
}

:global(.theme-shell[data-theme='light'] .export-btn-primary) {
    background: linear-gradient(135deg, #1d4ed8, #1e40af);
    color: #ffffff;
    box-shadow: 0 14px 26px rgba(29, 78, 216, 0.18);
}

:global(.theme-shell[data-theme='light'] .export-btn-primary:hover) {
    box-shadow: 0 18px 30px rgba(29, 78, 216, 0.22);
}

:global(.theme-shell[data-theme='light'] .export-btn-outline) {
    background: rgba(255, 255, 255, 0.94);
    color: #0f172a;
    border-color: rgba(15, 23, 42, 0.08);
}

:global(.theme-shell[data-theme='light'] .export-btn-outline:hover) {
    background: rgba(239, 246, 255, 0.96);
    border-color: rgba(29, 78, 216, 0.16);
}

:global(.theme-shell[data-theme='light'] .report-summary-pill-ok) {
    background: rgba(22, 163, 74, 0.1);
    border-color: rgba(22, 163, 74, 0.18);
    color: #15803d;
}

:global(.theme-shell[data-theme='light'] .report-summary-pill-ng) {
    background: rgba(225, 29, 72, 0.08);
    border-color: rgba(225, 29, 72, 0.14);
    color: #be123c;
}

:global(.theme-shell[data-theme='light'] .row-check) {
    accent-color: #1d4ed8;
}

:global(.theme-shell[data-theme='light'] .modal-overlay) {
    background: rgba(15, 23, 42, 0.16);
}

:global(.theme-shell[data-theme='light'] .modal-card) {
    background: linear-gradient(180deg, rgba(255, 255, 255, 0.99), rgba(247, 250, 252, 0.97));
    border-color: rgba(15, 23, 42, 0.08);
    box-shadow: 0 28px 70px rgba(15, 23, 42, 0.14);
}

:global(.theme-shell[data-theme='light'] .modal-close:hover) {
    background: rgba(219, 234, 254, 0.92);
    color: #1d4ed8;
}

:global(.theme-shell[data-theme='light'] .modal-input),
:global(.theme-shell[data-theme='light'] .modal-select) {
    background: rgba(255, 255, 255, 0.96);
    border-color: rgba(15, 23, 42, 0.08);
    color: #0f172a;
}

:global(.theme-shell[data-theme='light'] .modal-input:focus),
:global(.theme-shell[data-theme='light'] .modal-select:focus) {
    border-color: rgba(29, 78, 216, 0.28);
    box-shadow: 0 0 0 3px rgba(29, 78, 216, 0.1);
    background: rgba(255, 255, 255, 0.99);
}

:global(.theme-shell[data-theme='light'] .modal-ext) {
    background: rgba(241, 245, 249, 0.96);
    border-color: rgba(15, 23, 42, 0.08);
    color: #475569;
}

@media (max-width: 900px) {
    .report-toolbar {
        padding: 14px;
    }

    .report-toolbar__bar {
        width: 100%;
        grid-template-columns: 1fr 1fr;
    }

    .report-toolbar__footer {
        align-items: stretch;
    }

    .report-toolbar__meta {
        width: 100%;
    }

    .report-toolbar__actions {
        width: 100%;
        justify-content: flex-end;
    }

    .report-pagination {
        align-items: stretch;
    }

    .report-pagination__links {
        justify-content: flex-start;
    }
}

@media (max-width: 640px) {
    .report-toolbar__bar {
        grid-template-columns: 1fr;
    }
}
</style>
